apiVersion: apps/v1
kind: Deployment
metadata:
  name: bionexa-backend
  namespace: "2401042"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bionexa-backend
  template:
    metadata:
      labels:
        app: bionexa-backend
    spec:
      containers:
        - name: backend
          image: 127.0.0.1:3085/bionexa_kanishk/bionexa-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: bionexa-secrets
                  key: mongo_url
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/run/secrets/firebase/serviceAccountKey.json"
          volumeMounts:
            - name: firebase-service-account
              mountPath: /var/run/secrets/firebase
              readOnly: true
      volumes:
        - name: firebase-service-account
          secret:
            secretName: firebase-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bionexa-frontend
  namespace: "2401042"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bionexa-frontend
  template:
    metadata:
      labels:
        app: bionexa-frontend
    spec:
      containers:
        - name: frontend
          image: 127.0.0.1:30085/bionexa_kanishk/bionexa-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

