apiVersion: v1
kind: Service
metadata:
  name: bionexa-backend
  namespace: "2401042"
spec:
  selector:
    app: bionexa-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bionexa-frontend
  namespace: "2401042"
spec:
  selector:
    app: bionexa-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
