apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
  namespace: "2401199"
spec:
  selector:
    app: face-detection
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-detection-ingress
  namespace: "2401199"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: face.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: face-detection-service
                port:
                  number: 8000

